name: ecommerce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_sign_in: ^5.1.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  flutter_facebook_auth: ^3.5.1
  cloud_firestore: ^2.5.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf
